### ISSUE TITLE
About warehouse picking route simulation

### ISSUE THREAD

**Issue by Keenfortech** [samirsaci/pareto-warehouse-layout#1]
I am an engineer in logistics planning and engineering. Your warehouse picking route simulation is really impressive, this is an abrupt request, but may I know how you develop visualization of layout and picking route in the simulation? I'd like to do the same, but don't know how, and also don't know what tool can achieve that. could you please provide help? Thank you.
And please pardon me for leaving message like this. For I've gone through all the possible links in the website you shared, but anyhow, failed to find a proper way to get connected with you.

**Comment by samirsaci** [comment]
Sorry for my very late reponse.

Have you checked this series of articles: https://towardsdatascience.com/optimizing-warehouse-operations-with-python-part-1-83d02d001845

For the visualization, I am using SketchUP and Autocad.
